shotgunsoftware/tk-maya

engine.py

This removes a previous in the maya engine to ensure that at least a project context existed at startup. This check seems unnecessary and prevents the maya engine from starting up in a site-mode plugin setup. I think it was there to ensure that a maya project was always set by the engine - but we loosened that restriction a long time ago and the maya engine often runs with no project set. So I think it should be ok to just drop this check.
Need to run this through the automated QA before we merge with master.

#37277 Support for site context

---

engine.py

When docking an app widget in a Maya panel, raise the docked panel window to the top dock tab once Maya has settled.
Both 'maya.utils.executeDeferred' and 'maya.cmds.dockControl' used for this fix are documented as far back as Maya 2011.

#34202: Shotgun panel not launching focused and on top in Maya 2016.

---

engine.py
info.yml

When the Maya engine starts up, run the series of app instance commands listed in the 'run_at_startup' setting of the environment configuration yaml file.
For example, adding configuration option
```
run_at_startup:
- {app_instance: tk-multi-shotgunpanel, name: ''}
```
will make the engine launch the Shotgun panel automatically.

#37129: Ability of the Maya engine to run commands at startup.

---

engine.py
info.yml

This adds a `automatic_context_switch` option (which defaults to True for backwards compatibility), allow a user to turn off the automatic context switching behaviour in the maya engine.

#37900 Adds option to control automatic context switch.

---

.gitignore
plugins/basic/plug-ins/shotgun.py
plugins/basic/python/tk_maya_basic/plugin_engine.py
plugins/basic/python/tk_maya_basic/plugin_logging.py
plugins/basic/python/tk_maya_basic/plugin_logic.py

Same as #19 but merging into `develop/plugin` instead of master.

#34893: Run toolkit manager bootstrap logic in a background thread. (merges into develop/plugin)

---

engine.py
python/tk_maya/panel_generation.py

This new method will be called by the plug-in when shutting down the Maya engine:
```
engine.close_dialogs_and_panels()
engine.destroy()
```

#38349: Add a method to close dialogs and panels opened by the engine.

---

plugins/basic/python/tk_maya_basic/plugin_engine.py

The values of environment variables `SHOTGUN_ENTITY_TYPE` and `SHOTGUN_ENTITY_ID` are used to set the entity to launch the engine for. When they are missing, launch the engine in site context.

#38930: Launch Maya TaaP plug-in with different contexts.

---

plugins/basic/python/tk_maya_basic/plugin_engine.py

Adds a `SHOTGUN_SITE` environment variable alongside `SHOTGUN_ENTITY_TYPE` and `SHOTGUN_ENTITY_ID`. If `SHOTGUN_SITE` is set and not matching the site that we are currently logged in to, a warning in Maya is displayed:
```
https://wintermute.shotgunstudio.com but the plugin has been requested to launch 
with context Asset 1234 at https://foo.shotgunstudio.com. The plugin does not 
currently support switching between sites and the contents of SHOTGUN_ENTITY_TYPE
and SHOTGUN_ENTITY_ID will therefore be ignored. # 
```
At some point later, we can handle the extended implementation of this where the site is switched, the user is prompted for authentication etc., but this is outside the scope of basic zero config. For now, it's useful to just get a warning.

[minor] Added site warning

---

engine.py

The event handler wasn't being updated with the new context. This meant that when it was triggered, what it thought of as the "previous" context was no longer valid.
Also sets the Maya project on context change.

#39629: Recreates event handler on context change.

---

python/tk_maya/menu_generation.py

Add Shotgun context menu item _Jump to File System_ only when there are some file system locations.

#39476: 'Jump to File System' available only when there are some file system locations.

---

startup.py
startup/userSetup.py

Initial implementation for #38957 "auto detect maya paths" and #38959 "start up tk classic at maya app launch". Adds a MayaLauncher subclass of SoftwareLauncher to handle aspects of launching the Maya from within the Toolkit engine. Implements functionality required to launch TK classic on application launch, as tk-multi-launchapp does.

For #38957, implemented engine specific SofwareLauncher

---

info.yml
startup.py
startup/userSetup.py

Use the 'launch_builtin_plugin' engine setting value to determine which, if any, plugins to load when Maya launches.  If no plugins are found to load, fallback on bootstrapping the tk-maya engine from the environment instead.

For #39543, Load toolkit plugins on Maya launch

---

engine.py
python/tk_maya/__init__.py
python/tk_maya/panel_generation.py
python/tk_maya/panel_util.py

The opened Shotgun app panels docked in a Maya 2017 workspace are restored to their saved locations:
- when the user switches back to this workspace after displaying another workspace,
- when the user restarts Maya and the tk-maya engine is rebooted.
When switching from one workspace to another, the opened Shotgun app panels retain their current UI states.

#37575: Capture and recall Maya engine panel state in Maya 2017.

---

python/tk_maya/panel_generation.py

When embedding a Shotgun app panel into a Maya workspace control tab, give a minimum width to the workspace control.

#40171: Fix Maya 2017 panel sizing issues.

---

engine.py
python/tk_maya/__init__.py
python/tk_maya/panel_generation.py

Restore the persisted Shotgun app panels into their Maya workspace controls in the active Maya 2017 workspace.

#40170: Fix Shotgun app panels not restoring in Maya 2017.

---

plugins/basic/README.md
plugins/basic/info.yml
plugins/basic/plug-ins/shotgun.py
plugins/basic/python/tk_maya_basic/__init__.py
plugins/basic/python/tk_maya_basic/constants.py
plugins/basic/python/tk_maya_basic/plugin_engine.py
plugins/basic/python/tk_maya_basic/plugin_logging.py
plugins/basic/python/tk_maya_basic/plugin_logic.py
plugins/basic/shotgun.mod
startup.py
startup/userSetup.py

This enables the maya plugin to run both as a zero config "in-situ" part that lives in the engine (with no bundle cache) and as an independent component which can be built and deployed outside the tk eco system.
- The manifest has been cut down in order to enable the duality without having complicated build setups
- the plugin now handles both standalone and in-situ bootstraps
- Logging is less technical in its appearance and less is displayed in the console
- Added a sign up link on the menu if you are not logged in:
- removed some legacy logic which we won't need for the release
- improved detection of other plugins and tk classic

#38958 support for plugin and zero config modes + polish

---

startup.py

Updates the logic in the `MayaSoftwareLauncher.scan_software()` method to prefer information gathered from disk for the display name and icon of the corresponding launch command that is generated over information that is passed in from a Shotgun Software entity. Prior to this update, this fallback logic was reversed.

#40470, Update to scan software fallback logic 

---

startup.py

When Synergy data is used to determine the display name for a SoftwareVersion, first try to construct it from the "Name" and "NumericVersion" properties.  If one or both of those cannot be determined, then fallback on the "StringVersion" property.

[minor] Updated default display name from Synergy data

---

startup.py

See corresponding core PR here: 
https://github.com/shotgunsoftware/tk-core/pull/402
- Removes the name and icon parameters from the `SoftwareLauncher.scan_software()` interface.
- Now uses `SoftwareLauncher.get_standard_plugin_environment()` to generate context environment variables.

#40780 SoftwareLauncher interface tweaks

---

engine.py
python/tk_maya/menu_generation.py
python/tk_maya/panel_generation.py

Remove legacy log_* methods and use engine.logger.* instead.
These changes are for task: http://internal.shotgunstudio.int/page/10287#Ticket_41526_%5Btk-maya%5D%3A%20Finish%20switching%20to%20new%20style%20logging%20in%20the%20engine.

41526 Remove legacy log_* methods and use engine.logger.* instead.

---

engine.py

Now prevents duplicate shotgun menus when sgtk is disabled
It now only creates a new menu if one doesn't already exist, when sgtk is disabled.

#44166 prevent duplicate shotgun menus

---

engine.py

We have an issue where it is possible to deadlock Maya on import of QtWebEngineWidgets. If we know we are in 2018 on Windows, we set an environment variable that tells tk-core to not import that submodule.

For #44161: Maya 2018 Windows compatibility.

---

engine.py

We have an issue where it is possible to deadlock Maya on import of
QtWebEngineWidgets. If we know we are not in an officially supported
version (normally above 2018) on Windows, we set an environment variable
that tells tk-core to not import that submodule.

For #45564 Maya versions above 2018 compatibility

---

plugins/basic/python/tk_maya_basic/plugin_logic.py

Updating Maya's progress bar is NOT thread safe, so we need to ensure that all updates of progress there are processed in the main thread. The callback function registered with the bootstrapper is now only responsible for setting state on an object, and a QTimer running on the main thread updates the progress bar when necessary. This addresses a freeze/crash bug on launch of Maya when tk-core v0.18.153 is in use.

SG-9012: Ensures that progress updates are always run in the main thread during bootstrap.

---

engine.py

When you switch from an environment where `automatic_context_switch=False` to one where `automatic_context_switch=True`, this fix ensures that there's a `__watcher` instance currently registered with the engine before trying to call `stop_watching()`
Previously this would throw an error. In this case launching Maya from SG Desktop into the project environment where `automatic_context_switch=False`. Then using the File Manager, opening an asset which attempted to bring me into the asset_step environment where `automatic_context_switch=True`:
```
// Error: Shotgun tk-multi-workfiles2: Failed to change the work area to lookdev, Asset juggernaut!
Traceback (most recent call last):
File "/Users/kp/Library/Caches/Shotgun/bundle_cache/app_store/tk-multi-workfiles2/v0.10.0/python/tk_multi_workfile …
```

Ensure automatic_context_switch works when switching environments

---

engine.py

This resolves a long-standing problem with Qt window parenting in Maya on OS X. Dialogs will no longer fall behind Maya when they lose focus.
This fix is simple, but very opaque. It comes to us from the Maya dev team, but the people we've spoken to so far do not have an explanation for why it's required. This is the same solution they use for their own Python-based dialogs, so it should be safe.

SG-10146: Fix for window parenting on OS X.

---

hooks/tk-multi-publish2/basic/publish_session_geometry.py

Fixes a bug with exporting alembic files if there was a space somewhere in the path.
Previously if you had a path like `"c:\my folder\my_file.abc"` then it would error saying unsupported flags: `folder\my_file.abc` and `Can 't write to file: c:\my`.
This fix encapsulates the file path in a single quote string.

SG-14316 Fixes exporting alembic file paths with spaces

---

engine.py

Fixed an error we were getting in the script editor after launching Maya 2020. It prevented Workfiles2 to auto launch on startup.

SG-15270 Fixed a Workfiles2 error in Maya 2020

---

engine.py

Fixes a regression that was introduced in the Python 3 update.
This was previously a "!= darwin".
https://github.com/shotgunsoftware/tk-maya/commit/d1468a292776dcf0a29f6ea155dcfe7fd1f3ba32#diff-773b7e340b77c3c54109da863b41163ac971f899da59d8efcbfba7ce8a9c7e88L723-R723

Fix for show dialog.

---

hooks/tk-multi-publish2/basic/publish_session.py

- There are cases on custom plugins when `path` is stored under `local_properties`. This update prevent the publish plugin from breaking on `finalize` step.
- Needs https://github.com/shotgunsoftware/tk-multi-publish2/pull/168

SG-29238 Prevent AttributeError when path is missing

---

README.md

Follow up from #101. I'm updating the badges now that this engine has been tested with Python 3.10

Update badges and include Python 3.10

---

engine.py

This PR fixes the `RuntimeError` happening where network paths on Windows were double-escaped in `_set_project` and executed in cmds.workspace.

SG-33412 Error while saving a work file in maya.

---

engine.py
info.yml
plugins/basic/python/tk_maya_basic/plugin_logic.py
python/tk_maya/panel_generation.py
python/tk_maya/panel_util.py

This continues with the work done on [SG-31832-poc ](https://github.com/shotgunsoftware/tk-maya/tree/SG-31832-poc),  introduces compatibility with PySide6 for the Maya engine. It includes updating the import statements and the shiboken bindings to maintain functionality across different supported PySide versions.
Requires the changes made in tk-core [here](https://github.com/shotgunsoftware/tk-maya/pull/106). 
It is necessary to increase the minimum version of tk-core `requires_core_version` in the info.yml.

SG-31832 Add support for PySide6 and update shiboken bindings in Maya engine.

---

engine.py
info.yml

_Sgtk_ does not make sense anymore since #105
- Rename the `use_sgtk_as_menu_name` setting to `use_short_menu_name`
- Rename the short menu name "**Sgtk**" to "**FPTR**"
----
Closes #110, Closes #112

SG-35286 Rename the short menu name from "Sgtk" to "FPTR"

---

engine.py
info.yml

Adds `WindowMinimizeButtonHint` [WindowType](https://doc.qt.io/qtforpython-6/PySide6/QtCore/Qt.html#PySide6.QtCore.Qt.WindowType) to the engine dialog manager.
Add the `enable_dialogs_minimize_button` configuration in the tk-maya.yml settings file (in your config):
```yml
settings.tk-maya.project:
apps:
...
enable_dialogs_minimize_button: true
location: "@engines.tk-maya.location"
```
_Added minimize button_
-------
_All TK dialogs are located at the botton_

SG-36114 Add minimize button PoC

---

README.md
engine.py
info.yml
startup.py

Update the newest supported version from `2025` to `2026`.
Also, apply the following changes:
- Update the oldest compatible version from `2014` to `2022` (first version with Python 3)
- Update badges
- Fixup wrong regexp for detecting app versions

SG-38062 Add support for Maya 2026

---

engine.py
info.yml
startup.py

Differentiate warning messages between the oldest compatible version and the oldest supported version.
- shotgunsoftware/tk-3dsmax#49
- shotgunsoftware/tk-alias#215
- shotgunsoftware/tk-houdini#81
- shotgunsoftware/tk-mari#30
- shotgunsoftware/tk-motionbuilder#36
- shotgunsoftware/tk-nuke#116
- shotgunsoftware/tk-vred#134
Note: Please ignore the exact versions in the screenshots below. I had to tweak the code to issue those. 
* Error message when Maya version is older than the oldest **compatible** version
* Warning message when Maya version is older than the oldest **supported** version
* Warning message when Maya version is newer than the newest **supported** version

SG-32814 Review and unify code handling supported DCC versions
